// Renders emails/Confirmation.tsx (React Email + Tailwind → inline styles) into a static
// template with {{PLACEHOLDERS}}, so the API functions need no React/email runtime.
// Run: npm run email:build   (a test fails if the committed template is stale)
import { render } from '@react-email/render'
import { writeFileSync } from 'node:fs'
import { Confirmation } from '../emails/Confirmation'

export async function renderTemplate(): Promise<string> {
  return render(<Confirmation />)
}

export function templateModule(html: string): string {
  return (
    '// GENERATED by `npm run email:build` from emails/Confirmation.tsx. Do not edit by hand.\n' +
    `export const CONFIRMATION_HTML = ${JSON.stringify(html)}\n`
  )
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = new URL('../api/_lib/email-template.ts', import.meta.url)
  writeFileSync(out, templateModule(await renderTemplate()))
  console.log(`wrote ${out.pathname}`)
}
